### ISSUE TITLE
Criar componente que irá exibir um "Carousel"de "Cards"

### ISSUE THREAD

**Issue by MarciovsRocha** [MarciovsRocha/oneway-front#10]
### **História de Usuário**
**Descrição**

Como um usuário da plataforma,
Eu quero interagir com um componente de "Carousel" de "Cards",
Para visualizar e navegar pelos cards de forma intuitiva e responsiva.

**Critérios de Aceitação**

- Implementar um componente de "Carousel" de "Cards".

O carousel deve exibir os cards de forma contínua, em um loop.
Deve haver botões para avançar e retroceder no carousel.
Ao clicar em um card, ele deve se mover para o centro do carousel.

- Adicionar paginação ao carousel.

O carousel deve ter uma páginação representada por bolinhas na parte inferior.
Cada bolinha deve representar uma página do carousel, indicando a posição atual.

- Garantir responsividade do carousel.

O carousel deve se ajustar automaticamente a diferentes tamanhos de tela.
Os cards e a paginação devem ser visíveis e funcionais em dispositivos móveis e desktops.

**Comment by rafael-fxs** [comment]
Segue a evidência do carousel:

![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/4a9f0fa7-db22-415d-ae8e-4f9077eacec8)


![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/43e1a4b4-9e3c-40e4-8c3a-49172a457a26)


![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/0f7eb8dd-b533-4df3-be93-5fd5eede8970)
