### ISSUE TITLE
Criar a página de Cadastro

### ISSUE THREAD

**Issue by MarciovsRocha** [MarciovsRocha/oneway-front#13]
### **História de Usuário**
**Descrição**

Como um usuário interessado em se cadastrar,
Eu quero acessar uma página de cadastro que inclua uma imagem de viagem à esquerda e um formulário à direita contendo campos para criar senha, nome, e-mail, senha e confirmação de senha,
Para registrar meus dados de forma segura e acessar a plataforma.

**Critérios de Aceitação**

- Adicionar uma imagem de viagem à esquerda da página de cadastro.
A imagem deve ser relacionada ao contexto de viagem e visualmente atrativa.

- Criar um formulário à direita da página de cadastro.
O formulário deve incluir um card com o título "Criar senha".
Abaixo do título, deve haver campos para inserir nome, e-mail, senha e confirmação de senha.

- Implementar validações nos campos do formulário.
O campo de e-mail deve ter validação de e-mail.
O campo de senha deve ter no mínimo 6 caracteres.
O campo de confirmação de senha deve ser igual ao campo de senha.

- Adicionar botões na parte inferior do formulário.
Deve haver um botão "Cadastre-se" para enviar o formulário.
Deve haver um botão "Iniciar Sessão" para redirecionar para a página de login.

**Comment by rafael-fxs** [comment]
Segue a evidência:

![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/be11c439-f5c4-46b9-aa3e-2e28628e1046)
![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/ebbacc71-41f8-4a01-9906-375bd42d8d1a)
