### ISSUE TITLE
Criar Opção de menu do Usuário "Minhas Viagens" que irá exibir uma lista das viagens do usuário

### ISSUE THREAD

**Issue by MarciovsRocha** [MarciovsRocha/oneway-front#18]

**Comment by rafael-fxs** [comment]
![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/70693dc4-7ce5-48e4-9cef-111a0349248a)
![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/06161de8-98a2-43ad-ac15-a16fd66ea39a)
