### ISSUE TITLE
Criar componente Menu que ficará na parte superior da página Web

### ISSUE THREAD

**Issue by MarciovsRocha** [MarciovsRocha/oneway-front#4]
### **História de Usuário**
**Descrição**

Como um usuário da página Web,
Eu quero um componente de menu na parte superior da página que seja responsivo,
Para acessar facilmente diferentes funcionalidades, incluindo mudança para o modo escuro e acesso ao meu perfil de usuário.

**Critérios de Aceitação**

Criar um componente de menu responsivo.
O menu deve ficar na parte superior da página.
Deve incluir uma logo no canto esquerdo.
Os botões devem estar centralizados no menu.
Deve haver um botão com um ícone para ativar o modo escuro no canto direito.
Ao lado do botão de modo escuro, deve haver um botão com um ícone para acessar o perfil do usuário.

**Comment by rafael-fxs** [comment]
Segue a evidência do que foi desenvolvido.
Ainda precisa ser aprimorado conforme a necessidade.


![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/fa0d0a47-fc85-4a3f-9a89-d82e9ffbce29)

![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/fd61518a-5197-468f-93e3-5671293cb50a)

![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/1f75703b-5bd7-4526-a912-60f4ef2505a2)
