### ISSUE TITLE
Criar componente "Card" base

### ISSUE THREAD

**Issue by MarciovsRocha** [MarciovsRocha/oneway-front#9]
### **História de Usuário**
**Descrição**

Como um usuário da aplicação,
Eu quero ver um componente de "Card" no Angular,
Para visualizar informações de forma organizada e adicionar cards em uma lista conforme necessário.

**Critérios de Aceitação**

O card deve incluir uma imagem relevante ao conteúdo.
Deve conter um título que descreva o conteúdo do card.
Deve apresentar um texto que forneça detalhes adicionais sobre o card.
Deve ter um botão para adicionar o card em uma lista.
A imagem deve ser exibida de forma clara e ajustada ao card.
O título e o texto devem estar legíveis e bem posicionados no card.
O botão de adicionar deve estar visível e funcionar corretamente ao ser clicado.

**Comment by rafael-fxs** [comment]
Segue evidência do CARD básico criado.
Ainda vai precisar de melhorias conforme for usando.


![Image](https://github.com/MarciovsRocha/oneway-front/assets/5641578/0dcca699-ce6c-4a8b-ae66-8d87e25c305a)
